# Generated by Django 4.0.5 on 2022-07-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jblog', '0002_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
