# Generated by Django 4.0.5 on 2022-07-05 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jblog', '0004_blogpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
