# Generated by Django 4.0.5 on 2022-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jblog', '0004_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='region',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ("Farg'ona", "Farg'ona"), ('Navoiy', 'Navoiy'), ('Toshkent', 'Toshkent'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ("Qoraqalpag'iston", "Qoraqalpag'iston"), ('Xorazm', 'Xorazm')], default='Toshkent', max_length=250),
        ),
    ]
